name: viet_traider
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  event_bus: ^2.0.0
  file_picker: ^4.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cupertino_localizations: ^1.0.1
  flutter_html: ^2.2.0
  flutter_inappwebview: ^5.3.2
  flutter_secure_storage: ^4.2.0
  flutter_slidable: ^1.1.0
  flutter_sticky_header: ^0.6.0
  freezed_annotation: ^1.1.0
  html_editor_enhanced: ^2.4.0+1
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.8
  retrofit: ^3.0.1+1
  screen_capture_event: ^1.0.0+1
  sticky_headers: ^0.2.0
  syncfusion_flutter_pdfviewer: ^20.1.51-beta
  table_calendar: ^3.0.3
  url_launcher: ^6.0.10
  uuid: ^3.0.4
  scrollable_positioned_list: ^0.2.3
  flutter_icons: ^1.1.0
  fl_chart: ^0.50.1
  syncfusion_flutter_charts: ^20.1.51

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.6
  retrofit_generator: ^4.0.1
  url_launcher: ^6.0.10

  # Build Runner command: flutter pub run build_runner build --delete-conflicting-outputs
  # Create App Icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/images/
    - assets/images/logo/
    - assets/images/icon/
    - assets/locale/
    - assets/fonts/
    - assets/fonts/Roboto/

  fonts:
    - family: Symbol
      fonts:
        - asset: assets/fonts/Roboto/symbol.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic